-- ═════════════════════════════════════════════════════
-- Ventas_Tech_DB — Script SQL para esquema normalizado
-- Autor: Jorge Navarrete
-- Motor: PostgreSQL
-- Base de datos: ventas_tech_db
-- ═════════════════════════════════════════════════════

-- Nota:
-- La base de datos ventas_tech_db ya debe estar creada antes de ejecutar este script.
-- En PostgreSQL, CREATE DATABASE se ejecuta una sola vez desde otra base de datos.
-- Por eso, este script se enfoca en crear, limpiar y recargar las tablas del modelo.

-- Comando usado previamente:
-- create database ventas_tech_db;


-- ═════════════════════════════════════════════════════
-- 1. DROP TABLES
-- ═════════════════════════════════════════════════════
-- Se eliminan primero las tablas hijas, es decir, las tablas que dependen
-- de otras mediante foreign keys.
-- Esto evita errores de integridad referencial al volver a ejecutar el script.

drop table if exists ventas;
drop table if exists productos;
drop table if exists clientes;
drop table if exists categorias;


-- ═════════════════════════════════════════════════════
-- 2. CREATE TABLES — DDL + CONSTRAINTS
-- ═════════════════════════════════════════════════════

-- Tabla: categorias
-- Guarda las categorías de productos en una tabla separada.
-- Esto evita repetir el texto de la categoría dentro de productos
-- y ayuda a cumplir con la tercera forma normal (3NF).

create table categorias (
	id_categoria int generated by default as identity primary key,
	nombre_categoria varchar(50) not null,
	descripcion varchar(200)
);


-- Tabla: clientes
-- Guarda la información principal de cada cliente.
-- El email se define como not null y unique para evitar clientes duplicados
-- con el mismo correo.
-- La ciudad se marca como not null porque será útil para futuros análisis
-- de ventas por ubicación.

create table clientes (
	id_cliente int generated by default as identity primary key,
	nombre varchar(100) not null,
	email varchar(100) not null unique,
	ciudad varchar(50) not null,
	fecha_registro date not null
);


-- Tabla: productos
-- Guarda los productos vendidos por TechStore.
-- Cada producto pertenece a una categoría existente.
-- En PostgreSQL no existe tinyint(1) como en MySQL.
-- Por eso, activo se modela como smallint con una restricción check:
-- 1 = activo, 0 = inactivo.

create table productos (
	id_producto int generated by default as identity primary key,
	nombre_producto varchar(100) not null,
	id_categoria int not null,
	precio decimal(10,2) not null,
	stock int not null default 0,
	activo smallint not null default 1,

	constraint fk_productos_categorias
		foreign key (id_categoria)
		references categorias (id_categoria)
		on update cascade
		on delete restrict,

	constraint chk_productos_precio
		check (precio > 0),

	constraint chk_productos_stock
		check (stock >= 0),

	constraint chk_productos_activo
		check (activo in (0, 1))
);


-- Tabla: ventas
-- Es la tabla central del modelo.
-- Cada fila representa una transacción de venta.
-- Conecta clientes y productos mediante foreign keys.
-- La cantidad debe ser mayor que cero y el precio unitario debe ser positivo.

create table ventas (
	id_venta int generated by default as identity primary key,
	id_cliente int not null,
	id_producto int not null,
	cantidad int not null,
	precio_unitario decimal(10,2) not null,
	fecha_venta date not null,

	constraint fk_ventas_clientes
		foreign key (id_cliente)
		references clientes (id_cliente)
		on update cascade
		on delete restrict,

	constraint fk_ventas_productos
		foreign key (id_producto)
		references productos (id_producto)
		on update cascade
		on delete restrict,

	constraint chk_ventas_cantidad
		check (cantidad > 0),

	constraint chk_ventas_precio_unitario
		check (precio_unitario > 0)
);


-- ═════════════════════════════════════════════════════
-- 3. INSERT DATA — DML
-- ═════════════════════════════════════════════════════
-- Se cargan primero las tablas sin dependencias:
-- categorias y clientes.
-- Luego se cargan productos, que depende de categorias.
-- Finalmente se cargan ventas, que depende de clientes y productos.
--
-- No insertamos manualmente los IDs porque PostgreSQL los genera
-- automáticamente con generated by default as identity.

insert into categorias (
	nombre_categoria,
	descripcion
)
values
	('Computación', 'Laptops, PCs y monitores'),
	('Accesorios', 'Periféricos y complementos'),
	('Audio', 'Auriculares y parlantes'),
	('Almacenamiento', 'Discos y memorias');


insert into clientes (
	nombre,
	email,
	ciudad,
	fecha_registro
)
values
	('María López', 'maria@mail.com', 'Buenos Aires', '2024-01-05'),
	('Carlos Ruiz', 'carlos@mail.com', 'Córdoba', '2024-01-10'),
	('Ana Gómez', 'ana@mail.com', 'Rosario', '2024-02-01'),
	('Pedro Sanz', 'pedro@mail.com', 'Mendoza', '2024-02-15'),
	('Laura Torres', 'laura@mail.com', 'Tucumán', '2024-03-01');


insert into productos (
	nombre_producto,
	id_categoria,
	precio,
	stock,
	activo
)
values
	('Laptop Pro 15', 1, 1200.00, 15, 1),
	('Mouse Inalámbrico', 2, 28.00, 80, 1),
	('Monitor 4K 27"', 1, 450.00, 12, 1),
	('Auriculares BT Pro', 3, 120.00, 35, 1),
	('SSD Externo 1TB', 4, 130.00, 18, 1),
	('Teclado Mecánico', 2, 95.00, 40, 1);


insert into ventas (
	id_cliente,
	id_producto,
	cantidad,
	precio_unitario,
	fecha_venta
)
values
	(1, 1, 2, 1200.00, '2024-03-05'),
	(2, 2, 5, 28.00, '2024-03-06'),
	(3, 3, 1, 450.00, '2024-03-07'),
	(1, 4, 2, 120.00, '2024-03-08'),
	(4, 5, 3, 130.00, '2024-03-10'),
	(2, 6, 4, 95.00, '2024-03-11'),
	(5, 1, 1, 1200.00, '2024-03-12'),
	(3, 2, 8, 28.00, '2024-03-13'),
	(4, 4, 1, 120.00, '2024-03-14'),
	(5, 3, 2, 450.00, '2024-03-15');


-- ═════════════════════════════════════════════════════
-- 4. VALIDACIÓN
-- ═════════════════════════════════════════════════════
-- Estas consultas permiten confirmar que las cuatro tablas fueron creadas
-- y cargadas correctamente.

select * from categorias;

select * from clientes;

select * from productos;

select * from ventas;
