-- ══════════════════════════════════════════
-- BodegaTech — Script de Inventario
-- Autor: Jorge Navarrete
-- Fecha: 2026-07-08
-- Motor: PostgreSQL
-- ══════════════════════════════════════════

-- ── SECCIÓN DDL ──────────────────────────

-- DROP TABLE:
-- Eliminamos la tabla si ya existe para poder re-ejecutar el script
-- durante la práctica sin errores por tabla duplicada.

drop table if exists inventario;

-- CREATE TABLE:
-- Creamos la estructura de la tabla inventario con sus columnas, tipos de datos
-- y una clave primaria para identificar cada producto de forma única.
create table inventario (
	-- int porque el id_producto es un identificador numérico entero.
	-- generated by default as identity permite que postgresql genere el id automáticamente.
	-- primary key porque cada producto debe tener un identificador único y no nulo.
	id_producto int generated by default as identity primary key,

	-- varchar(100) porque el nombre del producto es texto corto con un límite razonable.
	-- not null porque todo producto debe tener nombre.
	nombre_producto varchar(100) not null,

	-- varchar(50) porque la categoría es texto corto, por ejemplo computación, audio o accesorios.
	-- not null porque todo producto debe estar clasificado.
	categoria varchar(50) not null,

	-- decimal(10,2) porque el precio es dinero y debe guardar decimales exactos.
	-- no usamos float porque puede generar imprecisiones en valores monetarios.
	-- check evita precios negativos.
	precio_unitario decimal(10,2) not null check (precio_unitario >= 0),

	-- int porque el stock_actual representa cantidad de unidades disponibles.
	-- not null porque un producto de inventario debe tener stock informado.
	-- check permite stock 0, pero evita stock negativo.
	stock_actual int not null check (stock_actual >= 0),

	-- int porque el stock_minimo representa el umbral mínimo de reposición.
	-- not null porque necesitamos saber cuándo reponer.
	-- check permite stock mínimo 0, pero evita valores negativos.
	stock_minimo int not null check (stock_minimo >= 0),

	-- date porque solo necesitamos guardar la fecha de ingreso, sin hora.
	-- not null porque todo producto cargado debe tener fecha de ingreso.
	fecha_ingreso date not null,

	-- en postgresql no usamos tinyint(1) como en mysql.
	-- usamos smallint y una restricción check para permitir solo 1 o 0.
	-- default 1 porque normalmente un producto nuevo se registra como disponible.
	-- 1 = disponible, 0 = descontinuado.
	activo smallint not null default 1 check (activo in (0, 1))
);

-- ── SECCIÓN DML ──────────────────────────

-- INSERT INTO:
-- Cargamos los 10 productos en la tabla inventario.
-- No incluimos id_producto porque PostgreSQL lo genera automáticamente.
insert into inventario (
	nombre_producto,
	categoria,
	precio_unitario,
	stock_actual,
	stock_minimo,
	fecha_ingreso,
	activo
)
values 
    ('Laptop Pro 15', 'Computación', 1200.00, 15, 3, '2024-01-10', 1),
    ('Mouse Inalámbrico', 'Accesorios', 28.00, 80, 10, '2024-01-10', 1),
    ('Monitor 4K 27"', 'Computación', 450.00, 12, 2, '2024-01-15', 1),
    ('Teclado Mecánico', 'Accesorios', 95.00, 40, 5, '2024-01-15', 1),
    ('Laptop Basic 14', 'Computación', 650.00, 20, 3, '2024-02-01', 1),
    ('Auriculares BT Pro', 'Audio', 120.00, 35, 5, '2024-02-01', 1),
    ('Hub USB-C 7 puertos', 'Accesorios', 45.00, 60, 10, '2024-02-10', 1),
    ('Webcam HD 1080p', 'Accesorios', 85.00, 25, 5, '2024-02-10', 1),
    ('SSD Externo 1TB', 'Almacenamiento', 130.00, 18, 3, '2024-03-01', 1),
    ('Parlante Bluetooth', 'Audio', 60.00, 45, 8, '2024-03-01', 1);

-- UPDATE ventas del día:
-- Venta de 3 unidades de Laptop Pro 15.
-- Restamos 3 al stock_actual solo del producto con id_producto = 1.
update inventario
set stock_actual = stock_actual - 3
where id_producto = 1;

-- Venta de 12 unidades de Mouse Inalámbrico.
-- Restamos 12 al stock_actual solo del producto con id_producto = 2.
update inventario
set stock_actual = stock_actual - 12
where id_producto = 2;

-- Venta de 5 unidades de Auriculares BT Pro.
-- Restamos 5 al stock_actual solo del producto con id_producto = 6.
update inventario
set stock_actual = stock_actual - 5
where id_producto = 6;

-- Producto Webcam HD 1080p fue descontinuado.
-- Pasamos activo a 0 solo para el producto con id_producto = 8.
update inventario
set activo = 0
where id_producto = 8;

-- Se verifica que todo haya salido correctamente
select *
from inventario;
